#!/usr/bin/env python3
"""Expand one calibrated subproblem per root into K/P/C candidate sets.

The original DeepSeek candidate is always preserved.  Missing dimensions are
generated by a local math model from the root solution and its decomposition.
The output is resumable and intended for the transfer-probe pilot; generated
rows still need the downstream counterfactual transfer test before selection.
"""

from __future__ import annotations

import argparse
import copy
import json
import random
import re
from pathlib import Path
from typing import Any

from capability_scaffold import stable_question_key
from calibrate_helpful_subproblems import minimal_plan, read_jsonl
from generate_subproblems_deepseek import normalize_answer


DIMENSIONS = ("knowledge", "planning", "calculation")


def as_text(value: Any) -> str:
    if value is None:
        return ""
    if hasattr(value, "tolist"):
        value = value.tolist()
    if isinstance(value, (list, tuple)):
        return "\n".join(str(item) for item in value if str(item).strip())
    return str(value)


def extract_json(text: str) -> dict[str, Any]:
    text = text.strip()
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.S | re.I)
    if fenced:
        text = fenced.group(1)
    decoder = json.JSONDecoder()
    for match in re.finditer(r"\{", text):
        try:
            value, _ = decoder.raw_decode(text[match.start() :])
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            return value
    raise ValueError("no JSON object found")


def candidate_from_value(
    value: dict[str, Any], anchor: dict[str, Any], dimension: str, model: str
) -> dict[str, Any]:
    subproblem = as_text(value.get("subproblem")).strip()
    answer = as_text(value.get("answer")).strip()
    relation = as_text(value.get("relation")).strip()
    source_step = as_text(value.get("source_step")).strip()
    verification = as_text(value.get("verification")).strip()
    if not subproblem or not answer or not source_step:
        raise ValueError(f"incomplete {dimension} candidate")
    if normalize_answer(answer) == normalize_answer(str(anchor["reference"])):
        raise ValueError(f"{dimension} candidate leaks the root answer")
    row = copy.deepcopy(anchor)
    row.update(
        {
            "id": f"{anchor['root_id']}::{dimension}",
            "dimension": dimension,
            "subproblem": subproblem,
            "subproblem_answer": answer,
            "relation": relation,
            "source_step": source_step,
            "verification": verification,
            "generator_model": model,
            "candidate_origin": "local_candidate_expansion",
        }
    )
    row["minimal_plan"] = minimal_plan(row, 12)
    if not row["minimal_plan"]:
        raise ValueError(f"unsafe or empty minimal plan for {dimension}")
    return row


def prompt_for(anchor: dict[str, Any], source: dict[str, Any], missing: list[str]) -> str:
    requested = ", ".join(missing)
    return f"""
Generate one distinct standalone prerequisite math problem for each requested
dimension: {requested}.

Requirements:
- Every subproblem must test a local capability genuinely used by the root solution.
- It must be easier than the root, independently solvable, and have a short exact answer.
- Do not reveal or ask for the root final answer.
- Knowledge tests a theorem/formula application; planning tests an intermediate target;
  calculation tests a concrete intermediate computation.
- Return valid JSON only, with this shape:
{{"candidates": {{"dimension": {{"subproblem": "...", "answer": "...",
"relation": "...", "source_step": "...", "verification": "..."}}}}}}

Root problem:
{anchor['question']}

Root final answer (leakage avoidance only):
{anchor['reference']}

Reference solution:
{as_text(source.get('solution'))[:7000]}

Knowledge decomposition:
{as_text(source.get('knowledge_components_parts'))[:5000]}

Planning decomposition:
{as_text(source.get('planning_skeleton_parts'))[:5000]}

Solution breakdown:
{as_text(source.get('solution_breakdown_parts'))[:7000]}

An existing verified candidate is shown only to enforce diversity:
{json.dumps({'dimension': anchor.get('dimension'), 'subproblem': anchor.get('subproblem'), 'answer': anchor.get('subproblem_answer')}, ensure_ascii=False)}
""".strip()


def generate_text(model: Any, tokenizer: Any, prompt: str, args: argparse.Namespace, seed: int) -> str:
    import torch

    messages = [
        {"role": "system", "content": "Create verifiable math subproblems. Output JSON only."},
        {"role": "user", "content": prompt},
    ]
    rendered = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(
        rendered,
        return_tensors="pt",
        truncation=True,
        max_length=args.max_input_tokens,
    ).to(args.device)
    torch.manual_seed(seed)
    generation = {
        "max_new_tokens": args.max_new_tokens,
        "do_sample": args.temperature > 0,
        "pad_token_id": tokenizer.eos_token_id,
        "eos_token_id": tokenizer.eos_token_id,
    }
    if args.temperature > 0:
        generation.update(temperature=args.temperature, top_p=args.top_p)
    with torch.inference_mode():
        output = model.generate(**inputs, **generation)
    return tokenizer.decode(output[0, inputs["input_ids"].shape[1] :], skip_special_tokens=True)


def run(args: argparse.Namespace) -> None:
    import pandas as pd
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    anchors = read_jsonl(args.anchors)
    if args.limit > 0:
        random.Random(args.seed).shuffle(anchors)
        anchors = anchors[: args.limit]
    source_rows = pd.read_parquet(args.source_data).to_dict(orient="records")
    source_by_question = {
        stable_question_key(str(row["question"])): row for row in source_rows
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    existing = read_jsonl(args.output) if args.output.exists() else []
    by_id = {str(row["id"]): row for row in existing}

    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)
    dtype = torch.bfloat16 if args.dtype == "bfloat16" else torch.float16
    model = AutoModelForCausalLM.from_pretrained(
        args.model,
        torch_dtype=dtype,
        low_cpu_mem_usage=True,
        trust_remote_code=True,
        attn_implementation="flash_attention_2",
    ).to(args.device)
    model.eval()

    errors: list[dict[str, Any]] = []
    for root_index, anchor in enumerate(anchors):
        anchor = copy.deepcopy(anchor)
        anchor["candidate_origin"] = "existing_deepseek_calibrated"
        by_id[str(anchor["id"])] = anchor
        missing = [
            dimension
            for dimension in DIMENSIONS
            if f"{anchor['root_id']}::{dimension}" not in by_id
        ]
        if not missing:
            continue
        source = source_by_question.get(stable_question_key(str(anchor["question"])))
        if source is None:
            errors.append({"root_id": anchor["root_id"], "error": "source row missing"})
            continue
        last_error = ""
        for attempt in range(args.retries):
            try:
                text = generate_text(
                    model,
                    tokenizer,
                    prompt_for(anchor, source, missing),
                    args,
                    args.seed + root_index * 100 + attempt,
                )
                value = extract_json(text)
                candidates = value.get("candidates", value)
                generated = {
                    dimension: candidate_from_value(
                        candidates[dimension], anchor, dimension, str(args.model)
                    )
                    for dimension in missing
                }
                by_id.update({str(row["id"]): row for row in generated.values()})
                print(
                    f"[{root_index + 1}/{len(anchors)}] {anchor['root_id']} "
                    f"generated={','.join(missing)}",
                    flush=True,
                )
                break
            except Exception as exc:
                last_error = f"{type(exc).__name__}: {exc}"
                print(
                    f"[{root_index + 1}/{len(anchors)}] attempt={attempt + 1} "
                    f"failed: {last_error}",
                    flush=True,
                )
        else:
            errors.append({"root_id": anchor["root_id"], "error": last_error})

        with args.output.open("w", encoding="utf-8") as handle:
            for row in by_id.values():
                handle.write(json.dumps(row, ensure_ascii=False) + "\n")

    complete_roots = 0
    dimensions_by_root: dict[str, set[str]] = {}
    for row in by_id.values():
        dimensions_by_root.setdefault(str(row["root_id"]), set()).add(str(row["dimension"]))
    complete_roots = sum(set(DIMENSIONS).issubset(value) for value in dimensions_by_root.values())
    summary = {
        "requested_roots": len(anchors),
        "complete_three_candidate_roots": complete_roots,
        "candidate_rows": len(by_id),
        "errors": errors,
        "model": str(args.model),
    }
    args.output.with_suffix(".summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--anchors", type=Path, required=True)
    parser.add_argument("--source-data", type=Path, required=True)
    parser.add_argument("--model", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--limit", type=int, default=32)
    parser.add_argument("--retries", type=int, default=3)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--dtype", choices=("float16", "bfloat16"), default="bfloat16")
    parser.add_argument("--max-input-tokens", type=int, default=4096)
    parser.add_argument("--max-new-tokens", type=int, default=800)
    parser.add_argument("--temperature", type=float, default=0.2)
    parser.add_argument("--top-p", type=float, default=0.95)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


if __name__ == "__main__":
    run(parse_args())
