#!/usr/bin/env bash
set -Eeuo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/home/powerleader/project/adaptive-scaffold-router}"
SELECTED_CANDIDATES="${SELECTED_CANDIDATES:?Set SELECTED_CANDIDATES}"
RUN_ROOT="${RUN_ROOT:?Set RUN_ROOT}"
EXIT_FILE="${EXIT_FILE:?Set EXIT_FILE}"
PRECONDITION_STEPS="${PRECONDITION_STEPS:-88}"
ROOT_ALIGNED_END_STEP="${ROOT_ALIGNED_END_STEP:-308}"
TOTAL_STEPS="${TOTAL_STEPS:-440}"
SAVE_FREQ="${SAVE_FREQ:-44}"
BASELINE_RUN_ROOT="${BASELINE_RUN_ROOT:-$PROJECT_ROOT/outputs/complete_four_way_ordered_20260815_155120}"

mkdir -p "$RUN_ROOT/logs"
trap 'code=$?; printf "%s\n" "$code" > "$EXIT_FILE"' EXIT
printf '%s\n' "full_1866_rcst_lcb_positive_2x8_fixed_440_updates_v1" > "$RUN_ROOT/method_label.txt"

SELECTED_CANDIDATES="$SELECTED_CANDIDATES" RUN_ROOT="$RUN_ROOT" \
BASELINE_RUN_ROOT="$BASELINE_RUN_ROOT" RUN_SUBPROBLEM_PROBE=1 \
LEARNABILITY_TRANSFER_ONLY=1 POSITIVE_TRANSFER_ONLY=1 \
PRECONDITION_STEPS="$PRECONDITION_STEPS" \
ROOT_ALIGNED_END_STEP="$ROOT_ALIGNED_END_STEP" TOTAL_STEPS="$TOTAL_STEPS" \
TRAIN_BATCH_SIZE=32 ROLLOUTS=8 PPO_MINI_BATCH_SIZE=32 \
MAX_RESPONSE_LENGTH=2048 SAVE_FREQ="$SAVE_FREQ" \
AUTO_EVAL=1 EVAL_GPUS=0 EVAL_N_GPUS=1 \
  bash "$PROJECT_ROOT/scripts/run_student_aware_root_aligned_only_2h100.sh"

echo "RCST LCB full-pool training and evaluation complete: $RUN_ROOT"
